services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cameras_db
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_NAME: cameras_db

volumes:
  mysql_data: {}
